// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: helloworld/genesis.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the helloworld module's genesis state.
type GenesisState struct {
	// this line is used by starport scaffolding # genesis/proto/state
	TimeoutPostList  []*TimeoutPost `protobuf:"bytes,6,rep,name=timeoutPostList,proto3" json:"timeoutPostList,omitempty"`
	TimeoutPostCount uint64         `protobuf:"varint,7,opt,name=timeoutPostCount,proto3" json:"timeoutPostCount,omitempty"`
	SendPostList     []*SendPost    `protobuf:"bytes,4,rep,name=sendPostList,proto3" json:"sendPostList,omitempty"`
	SendPostCount    uint64         `protobuf:"varint,5,opt,name=sendPostCount,proto3" json:"sendPostCount,omitempty"`
	PostList         []*Post        `protobuf:"bytes,2,rep,name=postList,proto3" json:"postList,omitempty"`
	PostCount        uint64         `protobuf:"varint,3,opt,name=postCount,proto3" json:"postCount,omitempty"`
	PortId           string         `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac0e42581531832b, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetTimeoutPostList() []*TimeoutPost {
	if m != nil {
		return m.TimeoutPostList
	}
	return nil
}

func (m *GenesisState) GetTimeoutPostCount() uint64 {
	if m != nil {
		return m.TimeoutPostCount
	}
	return 0
}

func (m *GenesisState) GetSendPostList() []*SendPost {
	if m != nil {
		return m.SendPostList
	}
	return nil
}

func (m *GenesisState) GetSendPostCount() uint64 {
	if m != nil {
		return m.SendPostCount
	}
	return 0
}

func (m *GenesisState) GetPostList() []*Post {
	if m != nil {
		return m.PostList
	}
	return nil
}

func (m *GenesisState) GetPostCount() uint64 {
	if m != nil {
		return m.PostCount
	}
	return 0
}

func (m *GenesisState) GetPortId() string {
	if m != nil {
		return m.PortId
	}
	return ""
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "dixitaniket.gitmony.helloworld.GenesisState")
}

func init() { proto.RegisterFile("helloworld/genesis.proto", fileDescriptor_ac0e42581531832b) }

var fileDescriptor_ac0e42581531832b = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x4a, 0x02, 0x41,
	0x18, 0xc7, 0x1d, 0x35, 0xcd, 0xc9, 0x28, 0x06, 0xa2, 0x45, 0x6a, 0x90, 0xf0, 0xb0, 0x14, 0xcc,
	0x52, 0xbd, 0x40, 0xd4, 0x21, 0x22, 0x0f, 0xb1, 0xd6, 0xa5, 0x8b, 0x68, 0x3b, 0xe8, 0x90, 0xee,
	0x0c, 0xce, 0x27, 0xe9, 0x5b, 0xf4, 0x58, 0x1d, 0x3d, 0x76, 0x8c, 0xdd, 0xf7, 0x88, 0x70, 0x76,
	0xdd, 0x1d, 0x0b, 0xf2, 0xf8, 0xfd, 0xbf, 0xfd, 0x7d, 0xbf, 0x3f, 0xec, 0x60, 0x67, 0xc8, 0x47,
	0x23, 0xf9, 0x26, 0x27, 0xa3, 0xc0, 0x1b, 0xf0, 0x90, 0x6b, 0xa1, 0x99, 0x9a, 0x48, 0x90, 0x84,
	0x06, 0x62, 0x26, 0xa0, 0x17, 0x8a, 0x57, 0x0e, 0x6c, 0x20, 0x60, 0x2c, 0xc3, 0x39, 0xcb, 0xbf,
	0x6e, 0x1c, 0x5b, 0x24, 0x88, 0x31, 0x97, 0x53, 0xe8, 0x2a, 0xa9, 0x21, 0xc1, 0x1b, 0x0d, 0x6b,
	0xad, 0x79, 0x18, 0xd8, 0xbb, 0x03, 0x6b, 0x97, 0xc7, 0x27, 0xdf, 0x45, 0x5c, 0xbf, 0x4d, 0x3a,
	0x74, 0xa0, 0x07, 0x9c, 0x3c, 0xe1, 0xbd, 0xf4, 0xf2, 0x83, 0xd4, 0xd0, 0x16, 0x1a, 0x9c, 0x4a,
	0xb3, 0xe4, 0xee, 0x5c, 0x9c, 0xb1, 0xff, 0xcb, 0xb1, 0xc7, 0x1c, 0xf3, 0x7f, 0xdf, 0x20, 0xa7,
	0x78, 0xdf, 0x8a, 0x6e, 0xe4, 0x34, 0x04, 0xa7, 0xda, 0x44, 0x6e, 0xd9, 0xff, 0x93, 0x93, 0x36,
	0xae, 0x2f, 0xdb, 0x67, 0xfe, 0xb2, 0xf1, 0xbb, 0x9b, 0xfc, 0x9d, 0x94, 0xf1, 0xd7, 0x68, 0xd2,
	0xc2, 0xbb, 0xab, 0x39, 0xd1, 0x6e, 0x19, 0xed, 0x7a, 0x48, 0xae, 0xf0, 0xb6, 0x5a, 0xf9, 0x8a,
	0xc6, 0xd7, 0xda, 0xe4, 0x33, 0xae, 0x8c, 0x22, 0x47, 0xb8, 0xa6, 0x32, 0x47, 0xc9, 0x38, 0xf2,
	0x80, 0x1c, 0xe2, 0xaa, 0x92, 0x13, 0xe8, 0x8a, 0xc0, 0x41, 0x4d, 0xe4, 0xd6, 0xfc, 0xca, 0x72,
	0xbc, 0x0b, 0xae, 0xef, 0x3f, 0x22, 0x8a, 0x16, 0x11, 0x45, 0x5f, 0x11, 0x45, 0xef, 0x31, 0x2d,
	0x2c, 0x62, 0x5a, 0xf8, 0x8c, 0x69, 0xe1, 0xf9, 0x7c, 0x20, 0x60, 0x38, 0xed, 0xb3, 0x17, 0x39,
	0xf6, 0xac, 0x2a, 0x5e, 0x5a, 0xc5, 0x9b, 0x79, 0xf6, 0x6b, 0x98, 0x2b, 0xae, 0xfb, 0x15, 0xf3,
	0x53, 0x2f, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x52, 0x26, 0x6f, 0xd1, 0x62, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TimeoutPostCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.TimeoutPostCount))
		i--
		dAtA[i] = 0x38
	}
	if len(m.TimeoutPostList) > 0 {
		for iNdEx := len(m.TimeoutPostList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TimeoutPostList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.SendPostCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.SendPostCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.SendPostList) > 0 {
		for iNdEx := len(m.SendPostList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SendPostList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.PostCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.PostCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.PostList) > 0 {
		for iNdEx := len(m.PostList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PostList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.PortId) > 0 {
		i -= len(m.PortId)
		copy(dAtA[i:], m.PortId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.PortId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PortId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.PostList) > 0 {
		for _, e := range m.PostList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.PostCount != 0 {
		n += 1 + sovGenesis(uint64(m.PostCount))
	}
	if len(m.SendPostList) > 0 {
		for _, e := range m.SendPostList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.SendPostCount != 0 {
		n += 1 + sovGenesis(uint64(m.SendPostCount))
	}
	if len(m.TimeoutPostList) > 0 {
		for _, e := range m.TimeoutPostList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.TimeoutPostCount != 0 {
		n += 1 + sovGenesis(uint64(m.TimeoutPostCount))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PortId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PortId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PostList = append(m.PostList, &Post{})
			if err := m.PostList[len(m.PostList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostCount", wireType)
			}
			m.PostCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PostCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendPostList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SendPostList = append(m.SendPostList, &SendPost{})
			if err := m.SendPostList[len(m.SendPostList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendPostCount", wireType)
			}
			m.SendPostCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SendPostCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutPostList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimeoutPostList = append(m.TimeoutPostList, &TimeoutPost{})
			if err := m.TimeoutPostList[len(m.TimeoutPostList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutPostCount", wireType)
			}
			m.TimeoutPostCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutPostCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
